# Generated by Django 2.2.5 on 2019-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=30)),
                ('long_url', models.URLField(unique=True, verbose_name='Url')),
            ],
        ),
    ]
