# Generated by Django 2.2.5 on 2019-09-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortmodel',
            name='short_url',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
